#!/usr/bin/env bash
case $(uname | tr '[:upper:]' '[:lower:]') in
  linux*)
    if ! grep -q "syncr" ~/.bashrc
    then
        echo "alias syncr='python3 $(pwd)/run.py'" >> ~/.bashrc
        echo "> Syncr: alias for Syncr has been added to bashrc"
        source ~/.bashrc
    else
        echo "> Syncr: alias already exists in bashrc"
    fi
    ;;
  darwin*)
    if ! grep -q "syncr" ~/.bashrc
    then
        echo "alias syncr='python3 $(pwd)/run.py'" >> ~/.bash_profile
        echo "> Syncr: alias for Syncr has been added to bashrc"
        source ~/.bash_profile
    else
        echo "> Syncr: alias already exists in bash_profile"
    fi
    ;;
  msys*)
    echo "> Syncr: Windows setup not supported yet."
    ;;
  *)
    echo "> Syncr: Cannot detect OS type."
    ;;
esac
